### ISSUE TITLE
Deadlock detection feature doesn't compile on stable Windows.

### ISSUE THREAD

**Issue by XAMPPRocky** [Amanieu/parking_lot#228]
While making #229 I found a error that I believe is unrelated to the CI, and is a bug in the library or at very least it's an undocumented requirement.  Which is that `deadlock-detection` will compile on stable macOS and Linux platforms, but not on Windows.

https://github.com/XAMPPRocky/parking_lot/runs/660453580#check-step-6

```
error[E0658]: use of unstable library feature 'ptr_cast'

   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\dbghelp.rs:110:74

    |

    |                 RtlLookupFunctionEntry(addr, &mut base, ptr::null_mut()).cast()
    |                                                                          ^^^^
    |

    = note: for more information, see https://github.com/rust-lang/rust/issues/60602


error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.

error: Could not compile `backtrace`.

warning: build failed, waiting for other jobs to finish...

error: build failed

##[error]Process completed with exit code 1.
```

**Comment by Amanieu** [comment]
It seems that the backtrace crate doesn't work on Rust 1.36. I think we should just disable the `deadlock_detection` feature on CI for 1.36.

**Comment by XAMPPRocky** [comment]
SGTM, I've updated #229 and it's all green https://github.com/XAMPPRocky/parking_lot/runs/660651699
